framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        # traduction en français par défaut et fallback en anglais et espagnol
        fallbacks:
            - en
            - fr
            - es