# CI vers planete hoster
name: CI
on:
  push:
    branches: [ master ] # branches à surveiller et a vérifier sur ton Git

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.PASS }} # variable d'environnement pour le mot de passe de la connexion ssh

    steps:
    - uses: actions/checkout@v2 # A vérifier car Git a changer de version vers la V3

    - name: Install sur le serveur
      run:
        sudo apt-get update && sudo apt-get install sshpass

    - name: Deploy
      run:
        sshpass -e ssh -o StrictHostKeyChecking=no -p 5022 ${{ secrets.USER }}@${{ secrets.HOST }}
        "cd public_html && git pull && php composer.phar install && php bin/console d:s:u --force && php bin/console c:c && php bin/console d:f:l -n"

